//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcWebMail.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int Id { get; set; }
        public string Subject { get; set; }
        public Nullable<int> FolderId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string NoteContent { get; set; }
        public string Category { get; set; }
    }
}
